# Generated by Django 4.0.3 on 2022-03-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_contactpersons'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpersons',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='contactpersons',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='contactpersons',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='contactpersons',
            name='skype',
            field=models.CharField(default='', max_length=50),
        ),
    ]
