# Generated by Django 4.0.3 on 2022-03-19 13:46

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_contactpersons_email_contactpersons_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('phnumber', phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None)),
                ('email', models.EmailField(default='', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contactpersons',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactpersons',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('billing_address', 'billing_address'), ('shipping_address', 'shipping_address'), ('customer_address', 'customer_address')], default='billing_address', max_length=20),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(default='', max_length=100)),
                ('search_text', models.CharField(default='', max_length=20)),
                ('sort_column', models.CharField(default='', max_length=50)),
                ('status', models.CharField(choices=[('sent', 'sent'), ('draft', 'draft'), ('overdue', 'overdue'), ('paid', 'paid'), ('void', 'void'), ('unpaid', 'unpaid'), ('partially_paid', 'partially_paid'), ('viewed', 'viewed')], default='draft', max_length=20)),
                ('date', models.DateTimeField(default=datetime.date(9999, 1, 1))),
                ('due_date', models.DateTimeField(default=datetime.date(9999, 1, 1))),
                ('due_days', models.IntegerField()),
                ('currency_code', models.CharField(choices=[('CZK', 'CZK'), ('EUR', 'EUR'), ('INR', 'INR'), ('HRK', 'HRK'), ('HUF', 'HUF'), ('RON', 'RON'), ('USD', 'USD')], default='INR', max_length=20)),
                ('total', models.FloatField()),
                ('balance', models.FloatField()),
                ('is_emailed', models.BooleanField(default=False)),
                ('reminders_sent', models.IntegerField()),
                ('payment_expected_date', models.DateTimeField(default=datetime.date(9999, 1, 1))),
                ('last_payment_date', models.DateTimeField(default=datetime.date(9999, 1, 1))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.customer')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.address'),
        ),
    ]
